POST http://localhost:3000/api/popular HTTP/1.1
Content-Type: application/json

{
  "carBrand": "Chrevrolet",
  "carModel": "Camaro",
  "carYear": "2020",
  "carPrice": "55.9",
  "Engine": "5.0, 4 Cilindros",
  "exteriorColor": "Gris",
  "interiorColor": "Negro",
  "Fuel": "Gasoline",
  "Transmission": "Automática",
  "Traction": "Trasera",
  "Type": [
    "Coupé",
    "Deportivo",
    "Muscle Car",
    "Pony Car"
  ],
  "Usage": "0",
  "Doors": "2",
  "Passengers": "4"
}

###

PUT http://localhost:3000/api/car/660b4f3e0f23b02e570a06e6 HTTP/1.1
Content-Type: application/json

{
    "carModel":"Corolla S"
}

###

DELETE http://localhost:3000/api/popular/660b81a0414c2a3e032c2193 HTTP/1.1
Content-Type: application/json


